### ISSUE TITLE
Equation width bugs

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#89]
We need custom CSS to fix the 100% width issue for fraction or square roots.  Here is one:

<img width="749" alt="screen shot 2016-07-11 at 10 48 03 am" src="https://cloud.githubusercontent.com/assets/191758/16734873/096757ae-4755-11e6-8ade-8893c648393b.png">

I started doing something like this here:

```CSS
.mathhack .katex .mfrac .frac-line {
    width: 10px;
}
```
https://github.com/shiffman/The-Nature-of-Code/blob/master/stylesheets/pdf/_math.scss#L8
