### ISSUE TITLE
code vs. comment width

### ISSUE THREAD

**Issue by shiffman** [shiffman/The-Nature-of-Code#93]
I'm not sure what is optimal but making a note here that I upped the width for code to avoid having to use `offset` as much as possible.

bf1011560d12d8913ef2fe0f302ac9d7aef5672c

What do you think @alterebro  @calxdesign?

```CSS
        .code {
            float: left;
            width: 55%;
        }
        .comment {
            float: right;
            width: 43%;
            p { margin: 0; }
        }
```
